### ISSUE TITLE
Research NER techniques

### ISSUE THREAD

**Issue by Parth27** [Parth27/savitar#1]
Research different NER techniques

**Comment by aarohi-joshi** [comment]
- [ ] Read up about NER

- [ ] Create server 

- [ ] Implement NER

- [ ] Trial run

- [ ] Final code

- [ ] Add necessary documentation (eg. comments)

- [ ] Make a comprehensive list of requirements
